---
name: Sjur Fortun
surname: Øfsteng
position: ""
pronouns: 
address: "Hertug skules veg 10, 2618 Lillehammer"
phone: +47 98043202
profilepic: "./img/sø.jpeg"
www: 
email: "sjurfortunofsteng@gmail.com"
twitter: 
github: sjurjo
linkedin: 
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
aboutme: "Jeg er fysioterapeut med lengre tids klinisk erfaring fra spesialist og primærhelsetjenesten. Jeg har en doktorgrad i helse- og treingsfysiologi fra Høgskolen I Innlandet/Norges Idrettshøgskole. Jeg er gift og har to barn."
output:
  vitae::awesomecv:
    page_total: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)

```

# Utdanning

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ note, ~ Where,
"Doktorgradutdanning", "2016-24", "Høgskolen i Innlandet", "I mine doktorgradprosjekter har jeg gjennomført omfattende eksperimentelle intervensjoner hvor vi har sammenlignet effekten av ulike styrketreningsbelastniger, treningsvolum og supplement på muskelstyrke og vekst i ulike miljø på trente og utrente personer.", "Lillehammer, Norge",
"Doktorgradutdanning", "2016-24", "Høgskolen i Innlandet", "Jeg har tillært meg programmeringsspråket R og brukt det i utarbeiding av vitenskapelige artikler og avhandlingen min. Et verktøy som jeg også bruker aktivt i visualering av data og analyser", "Lillehammer, Norge",
"Master i Idrettsfysioterapi", "2013-15", "Norges idrettshøgskole", "Mastergraden ga meg dypere innsikt i hvordan fysioterapeuten kan arbeide evidensbasert gjennom bl.a kritisk tolkning av forskningslitteraturen og hvordan vi kan integrere forskningen i en klinisk arbeidshverdag. Jeg hadde fordypningsoppgave i klassifiseringssystem av uspesifikke rygg-og nakkesmerter. Noe som ga meg innsikt i hvordan klinikere best mulig kan velge behandlingstiltak sett i lys av ulike symptomer i en heterogen pasientgruppe", "Oslo, Norge",
"Profesjonsbachelor i Fysioterapi", "2008-11", "University College Syd Danmark", "Bachelorgraden i Danmark ga meg en bred teoretisk grunnforståelse for menneskekroppens funksjon og oppbyggning knyttet sammen med det kliniske perspektivet", "Esbjerg, Danmark",
"Årsstudium i Idrett", "2005-06", "Høgskolen i Lillehammer", NA , "Lillehammer, Norge",
"Numedal Idrettsfolkehøgskole", "2004-05", "Idrettsfolkehøgskolen", NA, "Numedal, Norge",
"Artium",  "2004", "Vinstra videregående skole", NA, "Vinstra, Norge"
) %>%
  detailed_entries(Degree, Year, Institution, Where, note)
```

# Arbeidserfaring
<!--
* Mine ansettelsesforhold i fysioterapien har gitt meg bred erfaring i å kartlegge og tilrettelegge behandlingstiltak for en bred pasientgruppe innenfor ulik grad av KOLS, hjertesvikt, kroniske smerteproblematikker relatert til muskel-skjelettapparatet, post-operative ortopedi samt sentrale og perifere nevrologiske lidelser. Videre har jeg fått lengre erfaring i behandling av eldre pasientgrupper som opplever utfordringer med ADL-funksjoner relatert til redusert muskelfunksjon, pre-operative behandling av ortopedi, akutte muskel-skjelett plager hos både yngre og eldre personer. Utover individuell pasientoppfølgning har jeg i ansettelsesforholdene ved Grande Rehabilitering og Granheim Lungesjukehus arbeidet daglig med gruppebasert tilpasning i behandling av henholdsvis nevrologiske pasienter, smertepasienter og sårbare eldre personer på ulike funksjonsnivå både i svømmebasseng og sal.
-->
 
```{r}
library(tibble)
tribble(
  ~ Degree, ~note, ~ Year, ~ Institution, ~ Where,
  "Doktorgrad kandidat", "Seksjon for helse- og treningsfysiologi", "2016-2024", "Høgskolen i Innlandet", "Lillehammer",
  "Doktorgrad kandidat", "Som prosjektleder har jeg rekruttert, veiledet både studenter og forsøkspersoner, inkludert koordinering av eksterne aktører for å sikre kvalitet og gjennomføring av intervensjoner samt ansvar for de fysiologiske og molekylære målingene", "2016-2024", "Høgskolen i Innlandet", "Lillehammer",
  "Fysioterapeut", "Avtalehjemmel i Ringsaker Kommune, 50%", "aug 2022- des 23","Brumunddal Fysikalske Institutt", "Brumunddal",
  "Fysioterapeut", "Avtalehjemmel i Gausdal Kommune, 50% vikariat", "juni 2021- jan 22", "Gausdal Fysioterapi", "Gausdal",
  "Fysioterapeut", "Avtalehjemmel i Gausdal Kommune, 100% vikariat", "sept 2020- juni 21", "Gausdal Fysioterapi/Aktivklinikken", "Gausdal",
  "Fysioterapeut", "Avtalehjemmel i Lillehammer Kommune, 80% vikariat", "feb 2019- jan 20", "Aktivklinikken", "Lillehammer",
  "Fysioterapeut", "Tok initativ til å utvikle (i samarbeid med fysiologilabben på Høgskolen i Innlandet) en Return to Play test protokoll som er godkjent til bruk på forsikringspasienter hos IHS", "feb 2019- jan 20", "Aktivklinikken", "Lillehammer",
    "Fysioterapeut", "Jeg var i arbeidsperioden involvert i en prosjektgruppe omkring tematikken: optimalisering av samhandling mellom spesialist (Revmatismesjukehuset) og primærhelsetjenesten", "feb 2019- jan 20", "Aktivklinikken", "Lillehammer",
  "Fysioterapeut", "Avtalehjemmel i Ringsaker Kommune, 50% vikariat", " sept 2015- okt 16", "Fysioterapi Brumunddal", "Brumunddal",
  "Vitenskapelig assistent", "Forskningsprosjekt", "aug 2015- juni 16", "Høgskolen i Innlandet", "Lillehammer",
  "Fysioterapeut", "Rehabiliteringssenter,  80% vikariat", "april 2013- aug 13", "Grande rehabiliteringssenter", "Nes på Hedemarken",
  "Fysioterapeut", "Privatpraktiserende, 50%", "jan 2012- aug 13", "Moelv Fysioterapi", "Moelv",
  "Fysioterapeut", "Avtalehjemmel i Gausdal Kommune, 100% vikariat", "sept 2012- mar 13", "Gausdal Fysioterapi", "Gausdal",
  "Fysioterapeut", "Rehabiliteringssenter, 100% vikariat", "juni 2012- sept 12", "Grande rehabiliteringssenter", "Nes på Hedemarken",
  "Fysioterapeut", "Privatpraktiserende", "aug 2011- mai 12", "Gausdal Fysioterapi", "Gausdal",
  "Fysioterapeut", "Lungerehabiliteringssenter, 50% vikariat", "okt 2011- des 11", "Granheim Lungesjukehus", "Follebu"
 
) %>%
  detailed_entries(Degree, Year, Institution, Where, note)
```

# Undervisning

```{r}

library(tibble)
tribble(
  ~ Degree, ~note,  ~ Year, ~ Institution, ~ Where,
  "Undervisning i treningslære, emneansvar", NA, "2024", "Høgskolen i Innlandet", "Lillehammer",
   "Undervisning i treningslære, emneansvar", "Grunnleggende teori og praktiske øvinger", "2024", "Høgskolen i Innlandet", "Lillehammer",
  "Undervisning i biomekanikk: innføring i teori med praktiske øvinger", NA, "2023", "Høgskolen i Innlandet", "Lillehammer",
  "Sensur av 24 timers hjemmeeksamen i cellebiologi", NA, "2020", "Høgskolen i Innlandet", "Lillehammer",
  "Presentasjon av forskningsprosjekt og resultater: «Optimizing physical training and performance in soldiers» ", NA, "2018", "Cyber forsvaret", "Jørstadmoen",
  "Presentasjon av forskningsprosjekt og resultater: «Cyber Endurance»", NA, "2017", "Forsvarets forskningsinstitutt", "Kjeller",
  "Undervisning i biomekanikk og styrketrening", NA, "2017", "Høgskolen i Innlandet", "Lillehammer",
  "Presentasjon av forskningsprosjekt og resultater: «Effects of high vs. moderate protein intake during a 10-days military exercise with energy deficit on muscular performance (abstract)", NA, "2017", "In: Proceedings of the 22st Annual Congress of the European College of Sports Science; July 5-8", "MetropolisRuhr, Germany",
  "Behandler i nettverket til Idrettens skadetelefon", NA, "2019", "Idrettens helsesenter (IHS)", "Oslo",
  "Fysioterapeut/barmarkstrener for telemarkslandslaget", NA, "2012-2014", "Norges skiforbund", "Norge"
) %>%
  detailed_entries(Degree, Year, Institution, Where, note)
```

# Kurs

```{r}

library(tibble)
tribble(
  ~ Degree, ~note,  ~ Year, ~ Institution, ~ Where,
  "Generalised Linear (MIXED) (GLMM), Nonlinear (NLGLM) And General Additive Models (MIXED) (GAMM) (GNAM01), instructor Mark Andrews", NA, "2019", "PSstatistics", "Glasgow, Skottland",
  "Exercise in the Management and Prevention of Metabolic Diseases, host Brendan Gabriel", NA, "2019", "Karolinska Institutet", "Stockholm, Sverige",
  "Applied Logistic Regression, instructor Stanley Lemeshow, host Tor Strand", NA, "2018", "Innlandet Hospital Trust", "Lillehammer, Norge",
  "Evaluering av målemetoder, instructor Rolf Moe-Nilsson", NA, "2017", "Norges Idrettshøgskole", "Oslo, Norge",
  "Kvantitative design, instructor Arne Lervåg", NA, "2017", "Norges Idrettshøgskole", "Oslo, Norge",
  "Diagnostisk undersøkelse, instructor Joakim Halvorsen", NA, NA, "Nevrologi", "Oslo, Norge",
  "Pelvic, diastasis and exercise – Why and how?, host Kari Bø", NA, NA, "Nordic conference Womens health", "Norges Idrettshøgskole, Oslo",
  NA, NA, NA, "Motiverende intervju", "Nes på hedemarken, Norge",
  NA, NA, NA, "Red cord; neurac 1", "Oslo, Norge",
  NA, NA, NA, "Intra muskulær triggerpunkt behandling, teori og praksis; del 1 og 2 (P. Bogsti)", "Oslo, Norge",
  NA, NA, NA, "Kinesiotape kursrekke; KT 1-3", "Esbjerg, Danmark",
  NA, NA, NA, "Fot biomekanikk (Fysio1)", "Fredrikstad, Norge",
  NA, NA, NA, "Skulder-Evidensbasert undersøkelse og rehabilitering (NIMI)", "Oslo, Norge",
  NA, NA, NA, "Muscle energy techniques approaches in management of cervical, thoracic, pelvic pain and dysfunction (NFF)", "Oslo, Norge",
  NA, NA, NA, "Skanlab Concept", "Oslo, Norge",
  NA, NA, NA, "Antidoping Norge grunnopplæringskurs", "Oslo, Norge"
) %>% 
  detailed_entries(Degree, Year, Institution, Where, note)

#tribble(
#  ~Year, ~Type, ~Desc,
#  2018, "Logistisk regresjon", "1 uke med Lemenshow i logistisk regresjonsanalyse",
#  1911, "Kvinnehelse", "Mod"
#) %>%
#  brief_entries(
#    glue::glue("Kurs i {Type}"),
#    Year,
#    Desc
#  )
```

# Publications

```{r}
 bibliography_entries("publications.bib", "Publications") %>% 
  arrange(desc(author$family), issued)
```
 
```{r}
library(dplyr)
#knitr::write_bib(c("vitae", "tibble"), "packages.bib")

#bibliography_entries("packages.bib") %>%
#  arrange(desc(author$family), issued)
```
 

 


